<!doctype html>
<html>
<head>
   <title>$pagetitle$ | $sitetitle$</title>
   <meta charset="UTF-8" />
   <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" />
   <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css" />
   <link rel="stylesheet" href="nav.css" />
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-9">
        $contents$
      </div>
      <div id="nav" class="col-md-3">
        $nav$
      </div>
    </div>
  </div>
</body>
</html>
