name: Deploy Jekyll Site via FTP

on:
  push:
    branches:
      - master
      - feature_autodeploy
  workflow_dispatch:

jobs:
  ftp-deploy-action:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: 💎 Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Update to match your local ruby version (check with `ruby -v`)
          bundler-cache: true # runs 'bundle install' and caches gems automatically

      - name: 🔨 Build Site
        run: |
          bundle exec jekyll build --trace

      - name: 📂 Sync with FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./_site/
          server-dir: ./ 
          exclude: |
            a
            a/**
          dry-run: true  
          dangerous-clean-slate: true # Deletes files on server that aren't in _site (mirroring)